[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Hypick"
name = "ExplosivePresents"
description = "[v49] Allows presents to have a configurable chance to explode when opened"
websiteUrl = "https://github.com/Hypick122/ExplosivePresents"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "ExplosivePresents/bin/ExplosivePresents/ExplosivePresents.dll"
target = "ExplosivePresents.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
# https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = ["bepinex", "mods", "clientside", "serverside", "items"]
